### ISSUE TITLE
Add preselected tags option

### ISSUE THREAD

**Issue by xypnox** [vilvaathibanpb/react-search-multi-select#2]
Add a property such that we can define tags that are selected as passed through the props. This is useful if the same component is viewed for editing a set of tags instead of selecting them.

**Comment by vilvaathibanpb** [comment]
Hello @xypnox , Its a good idea. Do you want to raise a PR? Else let me add it over the weekend

**Comment by xypnox** [comment]
Hi @vilvaathibanpb , Thanks. I would like to add this functionality.
I would send a PR soon.

Sorry for the late response!

**Comment by vilvaathibanpb** [comment]
Sure.
